from django.utils.translation import gettext as _
_(r"")
_(r"Example 8")
_(r" Change Password")
_(r"Reset Password")
_(r"Hardware ")
_(r"Framework 7")
_(r"500")
_(r"Standing On The Train")
_(r"Lifestyle")
_(r"See All ")
_(r"eu dapibus risus aliquam etiam ut venenatis")
_(r"Dropdown ")
_(r"Ionic Framework 2")
_(r"Web Design")
_(r"Proin venenatis pellentesque arcu vitae ")
_(r"Example 18")
_(r"HTML5")
_(r" 								Nulla ante nulla, aliquet vel gravida non, finibus vel eros. Vestibulum lectus augue, placerat ac tincidunt rhoncus, vehicula ac tellus. Nullam a cursus ipsum. Pellentesque ornare mi sit amet nibh euismod gravida. Quisque in tempus odio. Fusce porttitor dolor ut tortor tristique, ut rhoncus nunc cursus. Morbi placerat lorem vel dictum maximus. Vivamus at sollicitudin turpis. Sed eu porta sem, et elementum tellus. 							")
_(r"Subscribe")
_(r" 									Magz is a HTML5 &amp; CSS3 magazine template based on Bootstrap 3. 								")
_(r"Forgot Password")
_(r"Mega Menu ")
_(r"Example 3")
_(r"Example 14")
_(r" 								Nulla facilisi. Donec mollis laoreet diam. Nullam suscipit pretium turpis at pellentesque. Donec suscipit libero nec pellentesque fringilla. Etiam dictum ut nulla eu vehicula. Nullam sed ultricies nisi. Etiam dapibus diam vitae gravida sagittis. 							")
_(r"Desktop")
_(r"Main Board")
_(r" For a submenu item")
_(r"Partner")
_(r"Donec consequat lorem quis augue pharetra")
_(r"Power Supply")
_(r"Example 1")
_(r"Ullamco Laboris")
_(r"Fermentum")
_(r"Example 2")
_(r"Dropdown Icons ")
_(r"Popular:")
_(r"jQuery")
_(r"Latest News")
_(r"Programming ")
_(r"Magz &mdash; Responsive HTML5 &amp; CSS3 Magazine Template")
_(r"Example 12")
_(r" My Account")
_(r"Follow us and stay in touch to get the latest news")
_(r" Settings")
_(r" - Collect from ")
_(r"Example 19")
_(r"Follow Us")
_(r"Error ")
_(r"Ionic Framework 3")
_(r"Troubleshoot ")
_(r"Office")
_(r"About Us ")
_(r"RAM")
_(r"Trending")
_(r"Example 4")
_(r"About")
_(r"More Templates ")
_(r"Creative Mind")
_(r"模板之家")
_(r"Example 17")
_(r"Page")
_(r"Nulla facilisis odio quis gravida vestibulum ")
_(r" You can add")
_(r" Your own items")
_(r"December 10, 2016")
_(r"Category")
_(r"503")
_(r"Example 10")
_(r"Menu")
_(r"Contact")
_(r"Home")
_(r"Duis aute irure dolor in reprehenderit in voluptate")
_(r"Mobile ")
_(r"Column 4")
_(r"Contact Us")
_(r"Software")
_(r" Comments")
_(r"at 6.00PM")
_(r"Register")
_(r"CSS3")
_(r"Hot")
_(r"Login")
_(r"Column 1")
_(r"Ionic Framework 1")
_(r"Example 7")
_(r" This is an example")
_(r"Pages ")
_(r"Column ")
_(r"Bootstrap 3")
_(r"Standard")
_(r"Featured Posts")
_(r"Example 6")
_(r"Newsletter")
_(r" 							COPYRIGHT &copy; MAGZ 2017. ALL RIGHT RESERVED. 							")
_(r"Single")
_(r"404")
_(r"Example 16")
_(r"Example 15")
_(r"Brainware")
_(r" 								Sed nec feugiat sem, nec ultrices orci. Duis ultrices ultricies fringilla. Aliquam convallis diam eu lectus porta, sit amet viverra nibh tincidunt. Etiam et luctus nisi. Integer posuere, augue at elementum aliquet, mauris ante dictum dui, eu pellentesque arcu ante eget libero. Sed consectetur fermentum felis sit amet eleifend. 							")
_(r"网页模板")
_(r"Travel")
_(r"Web")
_(r"Company Info")
_(r"Popular Tags ")
_(r"Example 11")
_(r"By subscribing you will receive new articles in your email.")
_(r"Example 9")
_(r"Authentication ")
_(r"Column 3")
_(r"We will tell you who we are")
_(r"403")
_(r"December 14, 2016")
_(r"Example 5")
_(r"Example 20")
_(r"Native")
_(r"Search")
_(r" 								Have a question? ")
_(r" 								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod 								tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 								quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 								consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse 								cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 								proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 							")
_(r"Hybrid ")
_(r"Internet")
_(r"About Us")
_(r"Column 2")
_(r"December 13, 2016")
_(r"Example 13")
_(r" Favorite")
_(r"Healthy")
_(r"AnguarJS")
_(r"Pellentesque")
_(r" Logout")
_(r" Mega menu is a new feature")
