from django.utils.translation import gettext as _
_(r"Shares")
_(r"Donec consequat lorem quis augue pharetra")
_(r"")
_(r"jQuery")
_(r"Example 12")
_(r"Mark Otto")
_(r"Creative Mind")
_(r"Standard")
_(r"Subscribe")
_(r"Example 2")
_(r"You May Also Like")
_(r"Popular Tags ")
_(r"Hardware ")
_(r"Standing On The Train")
_(r"Home")
_(r"Magz &mdash; Responsive HTML5 &amp; CSS3 Magazine Template")
_(r"CSS3")
_(r"Example 5")
_(r"Pages ")
_(r"Leave Your Response")
_(r"Single")
_(r"Bootstrap 3")
_(r" This is an example")
_(r"Example 8")
_(r"Example 14")
_(r"Troubleshoot ")
_(r"Ionic Framework 3")
_(r"Reset Password")
_(r"Internet")
_(r"Column ")
_(r" 									Magz is a HTML5 &amp; CSS3 magazine template based on Bootstrap 3. 								")
_(r"Dropdown Icons ")
_(r" You can add")
_(r"eu dapibus risus aliquam etiam ut venenatis")
_(r"Ionic Framework 2")
_(r"Write a Response")
_(r"Email ")
_(r" aliqua. Ut enim ad minim veniam, 												quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo. 											")
_(r"Category")
_(r"December 13, 2016")
_(r"Menu")
_(r"Trending")
_(r"网页模板")
_(r"Forgot Password")
_(r" 									20 									")
_(r"Error ")
_(r"Column 1")
_(r"24 Hours")
_(r"Web Developer")
_(r"By ")
_(r" - Collect from ")
_(r"Travel")
_(r"Page")
_(r"403")
_(r"December 14, 2016")
_(r"Example 1")
_(r"Example 6")
_(r"Website")
_(r" Facebook 									")
_(r"Example 3")
_(r"Login")
_(r"Ionic Framework 1")
_(r"Example 16")
_(r" Twitter 									")
_(r"3 Responses ")
_(r"Register")
_(r"Example 17")
_(r"Example 13")
_(r"Mega Menu ")
_(r" Favorite")
_(r"December 26, 2016")
_(r"Example 7")
_(r"Software")
_(r"About")
_(r"Example 18")
_(r"RAM")
_(r"模板之家")
_(r"Office")
_(r"December 10, 2016")
_(r"December 20, 2016")
_(r" Change Password")
_(r"Healthy")
_(r"Search")
_(r"About Us ")
_(r"Example 15")
_(r"Authentication ")
_(r"Power Supply")
_(r" Sharing is caring")
_(r"By subscribing you will receive new articles in your email.")
_(r"Nulla sagittis rhoncus nisi, vel gravida ante. Nunc lobortis condimentum elit, quis porta ipsum rhoncus vitae. Curabitur magna leo, porta vel fringilla gravida, consectetur in libero. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.")
_(r"Newsletter")
_(r" Settings")
_(r" 														Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 														consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse 														cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non 														proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 													")
_(r"Column 3")
_(r"Column 2")
_(r"Author")
_(r"Duis aute irure dolor in reprehenderit in voluptate velit")
_(r"December 21, 2016")
_(r" Your own items")
_(r"Example 11")
_(r" Logout")
_(r"Duis aute irure dolor in reprehenderit in voluptate")
_(r"Company Info")
_(r"Web")
_(r"500")
_(r"Proin venenatis pellentesque arcu vitae ")
_(r"Framework 7")
_(r" For a submenu item")
_(r"Example 10")
_(r"Desktop")
_(r" 							COPYRIGHT &copy; MAGZ 2017. ALL RIGHT RESERVED. 							")
_(r"Featured Posts")
_(r"International")
_(r"magna")
_(r"Native")
_(r"Example 20")
_(r"Follow Us")
_(r"Nulla facilisis odio quis gravida vestibulum ")
_(r"Brainware")
_(r"Advertisement")
_(r"Contact")
_(r" Linkedin 									")
_(r"HTML5")
_(r" My Account")
_(r" 												Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod 												tempor incididunt ut labore et dolore ")
_(r"Mobile ")
_(r" Email 									")
_(r"Response ")
_(r"Lifestyle")
_(r"Example 4")
_(r"Name ")
_(r"Partner")
_(r"503")
_(r"AnguarJS")
_(r"Example 9")
_(r"404")
_(r"Fusce ullamcorper elit at felis cursus suscipit")
_(r"Reply")
_(r"Hybrid ")
_(r"Web Design")
_(r"Send Response")
_(r"at 6.00PM")
_(r"Programming ")
_(r"Column 4")
_(r"Follow us and stay in touch to get the latest news")
_(r"1220")
_(r" 											Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod 											tempor incididunt ut labore et dolore magna aliqua. 											")
_(r" Google+ 									")
_(r"Popular:")
_(r"December 22, 2016")
_(r"More Templates ")
_(r"Recent Post")
_(r"Hot")
_(r"Lorem Ipsum Dolor Sit Amet Consectetur Adipisicing Elit")
_(r"Dropdown ")
_(r"Main Board")
_(r" Mega menu is a new feature")
_(r"Latest News")
_(r"John Doe")
_(r" Comments")
_(r"Example 19")
_(r"See All ")
