BB BBBBBBBB BB BBBBBBB
  XXXX XXXXXXXXX XXXXXXX XXX
BBBB
XXXX XXXXXXXXX XXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXX XXXX X XXXX XX XXX
    XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXXXXX X
      XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXX X XXXXX
      XXXXXX X XXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
    XXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X XXXXXXXXX X XXXX XXXXX
    X
XXXXXXXXX

XXXX XX XXXXXXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XX X XXXXX X XXXX XX XXXXXXXXXXXXXXXXXXX X XXX X XXXXXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX X X XXX XXX X X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXXXXXXXXXXXXXXXXXXXX X X XXXXXXXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX XXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXX X XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXX XX XXXXXXXX X XXXXXXXX X XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXX XX XXXXXXXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXX X XXXX X XXXX X XXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
BBBBB