XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX X

    XXX XXXXXXXXXXXXXXXXX X XXXXXXXX XX X
      XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX
    XX

    XXX XXXXXXXXXXXXXXXXXXX X X

      XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXX X XXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXX X XXXXXXXXXXXXXX  
          XXXXXXXXXXXX X XXXX
          XXXX X XXXXXXXXXXXXX XXXXX
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX X XXXX X XXX X XX X X XXXXX
          XX
          
      XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXXXXXX
        XXX XXX X XXXXXXXXXXXX
        XXX XXXXXXXXX X XX X XXXXXXXXXXXXX
        XXXXXXX X X XX X X XXXXXXXXXXXXX XXXX X 
            XXXXXXXXXXXXXXXXXXXX      
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX  
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XX
            XXXXXXXXXXXXXXXXXXX X XXXX
            XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX XXXXXXXX XXX XXXXXX      
            XXXXXXXXXXXXXXXXXXXX    
            XXXXXXXXXXXXXXX

            XXXXXXXXXXXXXXX
            XXXXXX X XXXX XXX X XX
        X
        XXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
      XX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXX XXXX XXXX XXXXXXX
      XXXXXXXXXXXXXXXX

      XXX XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX X XXXXXXXXXX X
        XXXXXXXXXXXXXXXX
      XX
    X

  XXXXX
XXXXXXXXX