XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX
	XXXXXXX
	XXXXXXXXXXXXXXXX XX X
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
		XXXXXXX XXX XXXXX XXXXX
		XXXXXXXXXXX XXX XXXXX XXXXX
		XXXXXXXX XXXX
		XXXXXXXXXX XXXXX
		XXXXXX XXXXXX
		XXXXXXXXXXXXX XXXXX
		XXXXXXX XXXXX
		XXXXXXXXXXX XXX XXXX XXXXX
		XXXXXXXXXXXXXXXX XXX XXXX XXXXX
		XXXXXXXXXXXXXXXXXXX XXX XXXX XXXXX
		XXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXXXXXX XXXX
	X
	XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X
		XXXXXXXXXXXXXXXXX XXXXX
		XXXXXXX XXX XXXXX XXXXXXXX
		XXXXXXXXXXX XXXXXXX XXX XXX XXXX
		XXXXXXXXXXXXXXXX XXXXXXX XXX XXX XXXX
		XXXXXXXXXXXXXXXXXXX XXXXXXX XXX XXX XXXX
		XXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX X
		XXXXXXX XXX XXXXX XXXXXXXX
		XXXXXXXXXX XXXXX
		XXXXXXXXXXXX XXXXX
		XXXXXX XXXXX
		XXXXXXX XXXXX
		XXXXXXXX XXX XXXXX
		XXXXXXX XXXXXXXX
		XXXXXXXXXXXXXXXXX XXXXXXXX
		XXXXXXXX XXXXXXXXXXXXX
		XXXXXX XXXXX
		XXXXXXXXXXXXXXXXXXX XXXXX
		XXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXXXXXXXXX XXXX
		XXXXXXXXXXXXXXX XXXX
	X
	XXXXXXXXXXX X
		XXXXXXXX XXXXX
		XXXXXXXXXXX XXXXX
		XXXXXXX XXXX XXXXX
		XXXXXXXX XXXXXX
		XXXXXX XXXXX
		XXXXXXXXXX XXXXXX
		XXXXXXXXX XXXXXXXXX
	X
	XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX X
		XXXXXXXXXXX XXXXX
	X
	XXXXXXXXXXXXXXXX X X
		XXXXXXXXXX XXXXX
		XXXXXX XXXXXXXX
	X
	XXXXXXXX
	XXXXXXXX
	XXXXXXXXXXXX X
		XXXXXXXXXXXXXXXXXXXXXXXXXXXX X
	        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	          XXXXX XXXXXXXXX

	          XXXXXXXXXXXXXXXX XXXXXX
	          XXXXXXXXXXX XXXXX

	          XXXXXXXXXX XXXXXXX

	          XXXXXXXXXXXXXXX XXXXX
	          XXXXXXXXXX XXXXXX
	          
	          XXXXXXXXXXXXX XXXX
	          XXXXXXXXXX XXXXXXXXXXXXXXXX
	        XXX
	    XXX
	X
    XXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
		XXXXXXXXXXXX XXXXXXXXX XXXXXX XX XXXXX XXXXXXXXXXXXXXXXX
		XXXXX XXX XXXXXXXX XXXXX XXX XXXXXXXX XXXXXXXXX XX XX XXXXXXXXX XXXX XXXX X XXXX XXX XXXXX X XXXXX XXX XXXXXXX XXXXXXXX XXX XXXXXXXXXXXX
		XXXX XXXXXXXXXXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
			XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
		XXXXXX
		
		XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
			XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXX	
	XXXXXXX
XXXXXX
