# Generated by Django 3.2.5 on 2021-09-04 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='views',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userarticledata',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.article'),
        ),
        migrations.AddField(
            model_name='userarticledata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='tag',
            index_together={('name',)},
        ),
        migrations.AddField(
            model_name='reprint',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.article'),
        ),
        migrations.AddField(
            model_name='reply',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.article'),
        ),
        migrations.AddField(
            model_name='reply',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='references',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.article'),
        ),
        migrations.AddField(
            model_name='likes',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.article'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collect',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.article'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together={('name',)},
        ),
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.article_htmlfield'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, db_index=True, to='index.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.article_excerpt'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='index.Tag'),
        ),
        migrations.AlterIndexTogether(
            name='views',
            index_together={('id', 'user', 'article', 'creation_time', 'modified_time')},
        ),
        migrations.AlterIndexTogether(
            name='userarticledata',
            index_together={('id', 'article', 'user')},
        ),
        migrations.AlterIndexTogether(
            name='reprint',
            index_together={('reprint_id', 'article')},
        ),
        migrations.AlterIndexTogether(
            name='reply',
            index_together={('to_reply_id', 'article', 'creation_time', 'from_user', 'to_user')},
        ),
        migrations.AlterIndexTogether(
            name='references',
            index_together={('references_id', 'article')},
        ),
        migrations.AlterIndexTogether(
            name='likes',
            index_together={('id', 'user', 'article', 'creation_time')},
        ),
        migrations.AlterIndexTogether(
            name='collect',
            index_together={('id', 'user', 'article', 'creation_time')},
        ),
        migrations.AlterIndexTogether(
            name='article',
            index_together={('author_user', 'title', 'creation_time', 'Likes_num', 'Forwarded')},
        ),
    ]
