from django.utils.translation import gettext as _
_(r"")
_(r"About Us ")
_(r"RAM")
_(r"Error ")
_(r"Example 9")
_(r"Example 14")
_(r"Example 8")
_(r"Column 1")
_(r"Password                                 ")
_(r"Example 3")
_(r"Email                                 ")
_(r"Donec consequat lorem quis augue pharetra")
_(r"See All ")
_(r"Ionic Framework 1")
_(r"Duis aute irure dolor in reprehenderit                                                             in voluptate")
_(r"Desktop")
_(r"at 6.00PM")
_(r" Logout")
_(r"500")
_(r"Magz &mdash; Responsive HTML5 &amp; CSS3 Magazine Template")
_(r"Example 15")
_(r"Troubleshoot ")
_(r"Newsletter")
_(r"jQuery")
_(r"Dropdown ")
_(r"Trending")
_(r"Subscribe")
_(r"Example 5")
_(r"Pages ")
_(r"Web Design")
_(r"Mega Menu ")
_(r" Your own items")
_(r"Column 3")
_(r"Example 17")
_(r"Contact")
_(r"Follow Us")
_(r"December 10, 2016")
_(r" -                         Collect from ")
_(r"AnguarJS")
_(r"Partner")
_(r"Popular:")
_(r"Example 7")
_(r"Already have an account?")
_(r"Programming ")
_(r"403")
_(r"Example 12")
_(r" This is an                                                 example")
_(r"Native")
_(r"Example 19")
_(r"Username                                 ")
_(r"Nulla facilisis odio quis gravida vestibulum ")
_(r"Example 10")
_(r"                             Magz is a HTML5 &amp; CSS3 magazine template based on Bootstrap 3.                         ")
_(r"Featured Posts")
_(r"Company Info")
_(r"Search")
_(r"Ionic Framework 2")
_(r"Email verification                                 ")
_(r"Office")
_(r"Authentication ")
_(r"Page")
_(r"Login")
_(r"Web")
_(r"Column ")
_(r"CSS3")
_(r"Latest News")
_(r"Example 18")
_(r"Single")
_(r" For a submenu                                                 item")
_(r"Proin venenatis pellentesque arcu vitae ")
_(r"Lifestyle")
_(r"More Templates ")
_(r"Follow us and stay in touch to get the latest news")
_(r"December 14, 2016")
_(r" You can add")
_(r"Standing On The Train")
_(r" Favorite")
_(r"404")
_(r"Creative Mind")
_(r"Travel")
_(r"503")
_(r"Software")
_(r"Dropdown Icons ")
_(r"Hot")
_(r"Example 4")
_(r"get verification code")
_(r"Category")
_(r"                     COPYRIGHT &copy; MAGZ 2017. ALL RIGHT RESERVED.                     ")
_(r"Reset Password")
_(r"Column 4")
_(r"Example 2")
_(r"Hybrid ")
_(r"Example 11")
_(r"Internet")
_(r"December 13, 2016")
_(r"Example 13")
_(r"Bootstrap 3")
_(r"eu dapibus risus aliquam etiam ut venenatis")
_(r"First Name                                 ")
_(r"Menu")
_(r"Mobile ")
_(r"网页模板")
_(r"Example 1")
_(r"Standard")
_(r"Column 2")
_(r"Forgot Password")
_(r"About")
_(r"Brainware")
_(r"Ionic Framework 3")
_(r"Main Board")
_(r"Example 6")
_(r"Power Supply")
_(r"Hardware ")
_(r"Framework 7")
_(r" Change Password")
_(r"Example 20")
_(r" Settings")
_(r"Popular Tags                         ")
_(r"Home")
_(r"Healthy")
_(r"HTML5")
_(r" Mega menu is a new                                                 feature")
_(r"By subscribing you will receive new articles in your email.")
_(r"Register")
_(r"模板之家")
_(r" My Account")
_(r" Comments")
_(r"Last Name                                 ")
_(r"Example 16")
