XXXXXXXXX XXXXX
XXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX    

    XXXXXXXXXXXXXXX
    
    XXXXX XXXXXXXXXXXXXXXX 
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXX X XXXX XX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXX XX

    XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XX

    BB BBBBBBBB BB BBBBBBB
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    BBBB
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    BBBBB


    BB BBBBBBBBBB BB BBBBBBBBB BBBBB BBBBBBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
    BBBBB

  XXXXXXX

  XXXXXX
    
  XXXX XXXXXXXXXXXXXXXXXX

     FFFFFFFF

    XXXX XXXXXXXXXXXX
      XXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBB XXXXXXXXXXX XX XXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXBBBBB
    XXXXXX

  XXXXXX
  
  

  BB BBBBBBBBBB
    BB BBBBBBBB BB BBBBBBB
      XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX XX XX X XXXXXXX X XXXXXXXXX X
        XXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBB
      XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXX XX XX X XXXXXXX X XXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
  BBBBB

  BBBBBBB BBBBBBBBBBBBBB

  BB BBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBB
  BBBBB

  BB BBBBBBBB BB BBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXX XXX XXXXX XXX XXXXXX XXX XX XXXX XXX XXXXXXXXXXXXXXXXXXXX
  BBBBB
  XXXXXXX
XXXXXXX