# Generated by Django 3.2.5 on 2021-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinymceDocumentSummary',
            fields=[
                ('file_path', models.FilePathField()),
                ('file_url', models.URLField()),
                ('file_md5', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
