from django.utils.translation import gettext as _
_(r"")
_(r"More")
_(r" 									Hot News 									")
_(r" 														Lorem ipsum dolor sit amet, consectetur adipisicing elit. 													")
_(r" Featured")
_(r"Best Of The Week")
_(r" Comments 									")
_(r"Previous")
_(r"Photos")
_(r"Just Another News ")
_(r"Videos 								")
_(r"Trending Tags")
_(r"By subscribing you will receive new articles in your email.")
_(r"Sidebar")
_(r"Next")
_(r"Popular ")
_(r"Latest News")
_(r"Posts")
_(r" Recomended 									")
_(r"+2")
_(r"Sponsored")
_(r"See All ")
_(r"See All Authors")
_(r"Focus")
_(r"Newsletter")
_(r"Tip!")
