# Generated by Django 3.2.5 on 2021-09-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forget', '0002_usermd5_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermd5',
            name='user_md5',
            field=models.CharField(max_length=32, verbose_name='user_md5'),
        ),
    ]
