XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
  XXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXX
    XXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
  XXXXX
  XXXX XXXXXXXXXXXXXXXX
    XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
  XXXXXX
XXXXXXXXX

XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
      XXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXX XXX XXXXX XX XXXX XXXXX XX XXX XX XXX XXXX XXXXXXX XXX XXXX XXXXXXX XXX XX XXX XXXXXXX XXX
        XXXXXXXXXX
        XXX XXXXXXXXXXX XX XX XXXXXXX XX XXXX XXX XXXXXXXXXXXXX
    XXXXXXXX
  XXXXXXXXXX
XXXXXXXXXX
XXXXXXX
XXXXXXX