# Generated by Django 3.2.5 on 2021-09-11 13:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='TinifyException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('Exception', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TinifyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('masage', models.CharField(max_length=128)),
            ],
        ),
    ]
